-- Fix image URLs by matching on nom (name) instead of id
UPDATE menu_items SET image_url = 'img/sandwich-shawarma.jpg' WHERE nom = 'Shawarma Poulet';
UPDATE menu_items SET image_url = 'img/sandwich-chich-taouk.jpg' WHERE nom = 'Chich Taouk';
UPDATE menu_items SET image_url = 'img/sandwich-boeuf.jpg' WHERE nom = 'Shawarma Boeuf';
UPDATE menu_items SET image_url = 'img/sandwich-falafel.jpg' WHERE nom = 'Falafel';
UPDATE menu_items SET image_url = 'img/sandwich-veggie.jpg' WHERE nom = 'Veggie';
UPDATE menu_items SET image_url = 'img/sandwich-foie-volaille.jpg' WHERE nom = 'Foie de Volaille';
UPDATE menu_items SET image_url = 'img/sandwich-kafta.jpg' WHERE nom = 'Kafta';
UPDATE menu_items SET image_url = 'img/sandwich-soujouk.jpg' WHERE nom = 'Soujouk';
UPDATE menu_items SET image_url = 'img/formule-1.jpg' WHERE nom = 'Formule 1';
UPDATE menu_items SET image_url = 'img/formule-2.jpg' WHERE nom = 'Formule 2';
UPDATE menu_items SET image_url = 'img/formule-3.jpg' WHERE nom = 'Formule 3';
UPDATE menu_items SET image_url = 'img/formule-4.jpg' WHERE nom = 'Formule 4';
UPDATE menu_items SET image_url = 'img/kafta-mechoui.jpg' WHERE nom = 'Kafta Méchoui';
UPDATE menu_items SET image_url = 'img/houmous.jpg' WHERE nom = 'Houmous';
UPDATE menu_items SET image_url = 'img/moutabal.jpg' WHERE nom = 'Moutabal';
UPDATE menu_items SET image_url = 'img/taboule.jpg' WHERE nom = 'Taboulé';
UPDATE menu_items SET image_url = 'img/salade-moine.jpg' WHERE nom = 'Salade du Moine';
UPDATE menu_items SET image_url = 'img/plat-jour.jpg' WHERE nom = 'Moussaka';
UPDATE menu_items SET image_url = 'img/feuilles-vigne.jpg' WHERE nom = 'Feuilles de Vignes';
UPDATE menu_items SET image_url = 'img/mouhalabieh.jpg' WHERE nom = 'Mouhalabieh';
UPDATE menu_items SET image_url = 'img/namoura.jpg' WHERE nom = 'Namoura';
UPDATE menu_items SET image_url = 'img/baklawas.jpg' WHERE nom = 'Baklawas';
UPDATE menu_items SET image_url = 'img/duo-sables.jpg' WHERE nom = 'Duo Sablés';
UPDATE menu_items SET image_url = 'img/coca.jpg' WHERE nom = 'Coca-Cola';
UPDATE menu_items SET image_url = 'img/fanta.jpg' WHERE nom = 'Fanta';
UPDATE menu_items SET image_url = 'img/oasis.jpg' WHERE nom = 'Oasis Tropical';
UPDATE menu_items SET image_url = 'img/lipton.jpg' WHERE nom = 'Lipton Pêche';
UPDATE menu_items SET image_url = 'img/7up.jpg' WHERE nom = '7Up';
UPDATE menu_items SET image_url = 'img/coca-zero.jpg' WHERE nom = 'Coca-Cola Zero';
UPDATE menu_items SET image_url = 'img/perrier.jpg' WHERE nom = 'Perrier';
UPDATE menu_items SET image_url = 'img/eau.jpg' WHERE nom = 'Eau Plate';
UPDATE menu_items SET image_url = 'img/falafel.jpg' WHERE nom LIKE 'Falafel%pièce%';
UPDATE menu_items SET image_url = 'img/fattayer.jpg' WHERE nom = 'Fattayer';
UPDATE menu_items SET image_url = 'img/sambousek-fromage.jpg' WHERE nom = 'Samboussek Fromage';
UPDATE menu_items SET image_url = 'img/rkakat.jpg' WHERE nom = 'Rikakat Fromage';
UPDATE menu_items SET image_url = 'img/sambousek-viande.jpg' WHERE nom = 'Samboussek Viande';
UPDATE menu_items SET image_url = 'img/kebbe.jpg' WHERE nom = 'Kebbé';
